version: '3.9'

services:
  # Message Broker
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    restart: always
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    volumes:
      # - data_kafka:/var/run/docker.sock
      - data_kafka:/kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LOG_DIRS=/logs
    depends_on:
      - zookeeper
    restart: always
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:  
      - 8081:8080
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    depends_on:
      - zookeeper
      - kafka

  # Databases
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - data_mongo:/data/db
    restart: always

  # Services
  post:
    container_name: post
    build: ./post
    volumes:
      - ./post:/app
    environment:
      - PORT=8080
      - MONGO_URL=mongodb://mongo:27017/post
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - mongo
      - kafka
    restart: always
  comment:
    container_name: comment
    build: ./comment
    volumes:
      - ./comment:/app
    environment:
      - PORT=8080
      - MONGO_URL=mongodb://mongo:27017/comment
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - mongo
      - kafka
    restart: always
  query:
    container_name: query
    build: ./query
    volumes:
      - ./query:/app
    environment:
      - PORT=8080
      - MONGO_URL=mongodb://mongo:27017/query
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - mongo
      - kafka
    restart: always

  # API Gateway
  api_gateway:
    container_name: api_gateway
    build: ./api_gateway
    ports:
      - 5000:8080
    volumes:
      - ./api_gateway:/app
    environment:
      - PORT=8080
      - SERVICE_POST_HOST=http://post:8080
      - SERVICE_COMMENT_HOST=http://comment:8080
      - SERVICE_QUERY_HOST=http://query:8080 
    depends_on:
      - post
      - comment
      - query
    restart: always

volumes:
  data_kafka:
  data_mongo:
