apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment
  template:
    metadata:
      labels:
        app: comment
    spec:
      containers:
        - name: comment
          image: dreamcheck/comment
          env:
            - name: PORT
              value: "4002"
            - name: MONGO_URL
              value: "mongodb://mongo-srv:27017/comment"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-srv:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: comment-srv
spec:
  selector:
    app: comment
  type: ClusterIP
  ports:
    - name: comment
      protocol: TCP
      port: 4002
      targetPort: 4002
