apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
        - name: post
          image: dreamcheck/post
          env:
            - name: PORT
              value: "4001"
            - name: MONGO_URL
              value: "mongodb://mongo-srv:27017/post"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-srv:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: post-srv
spec:
  selector:
    app: post
  type: ClusterIP
  ports:
    - name: post
      protocol: TCP
      port: 4001
      targetPort: 4001
