apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: query
          image: dreamcheck/query
          env:
            - name: PORT
              value: "4003"
            - name: MONGO_URL
              value: "mongodb://mongo-srv:27017/query"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-srv:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: query-srv
spec:
  selector:
    app: query
  type: ClusterIP
  ports:
    - name: query
      protocol: TCP
      port: 4003
      targetPort: 4003
